/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repasointroduccionjava;

import herencia.Basico;
import herencia.BasicoAdministrativo;
import herencia.BasicoGerente;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Salario extends javax.swing.JFrame {

    Basico basico = new Basico();
    BasicoAdministrativo basicoAdministrativo = new BasicoAdministrativo();
    BasicoGerente basicoGerente = new BasicoGerente();
    
    /**
     * Creates new form Salario
     */
    public Salario() {
        initComponents();
        lblresultado.setVisible(false);
        lbltipoempleado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txthorasTrabajadas = new javax.swing.JTextField();
        txtvalorHora = new javax.swing.JTextField();
        btncalcular = new javax.swing.JButton();
        lblresultado = new javax.swing.JLabel();
        btnvolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rbempNormal = new javax.swing.JRadioButton();
        rbempAdministrativo = new javax.swing.JRadioButton();
        lblresultado1 = new javax.swing.JLabel();
        rbempGerente = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        lbltipoempleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText(">>Opción: Salario persona.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Horas trabajadas:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Valor hora:");

        btncalcular.setText("Calcular");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        lblresultado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblresultado.setText("Resultado");

        btnvolver.setText("<< Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultado:");

        rbempNormal.setText("Normal");
        rbempNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbempNormalActionPerformed(evt);
            }
        });

        rbempAdministrativo.setText("Administrativo");
        rbempAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbempAdministrativoActionPerformed(evt);
            }
        });

        lblresultado1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblresultado1.setText("Tipo Empleado");

        rbempGerente.setText("Gerente");
        rbempGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbempGerenteActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de Empleado:");

        lbltipoempleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltipoempleado.setText("Empleado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnvolver))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtvalorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txthorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btncalcular, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 29, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbempNormal)
                                    .addComponent(rbempAdministrativo)
                                    .addComponent(lblresultado1)
                                    .addComponent(rbempGerente)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblresultado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltipoempleado)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lblresultado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txthorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbempNormal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtvalorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbempAdministrativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncalcular)
                    .addComponent(rbempGerente))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblresultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbltipoempleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnvolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        
        if(!rbempNormal.isSelected() && !rbempAdministrativo.isSelected() && !rbempGerente.isSelected()){
            JOptionPane.showMessageDialog(null, 
                    "Debes seleccionar un tipo de empleado",
                    "Mensaje de información incompleta",
                    JOptionPane.WARNING_MESSAGE);
        }else{
            try{
        if(rbempNormal.isSelected()){
            basico.setHorasTrabajadas(Double.parseDouble(txthorasTrabajadas.getText()));
            basico.setValorHora(Double.parseDouble(txtvalorHora.getText()));
            lblresultado.setText(String.valueOf(basico.calcular()));
            lblresultado.setVisible(true);
            lbltipoempleado.setText(basico.realizarFuncion("Hacer aseo"));
            lbltipoempleado.setVisible(true);
            
        }else{
            if(rbempAdministrativo.isSelected()){
            basicoAdministrativo.setHorasTrabajadas(Double.parseDouble(txthorasTrabajadas.getText()));
            basicoAdministrativo.setValorHora(Double.parseDouble(txtvalorHora.getText()));
            lblresultado.setText(String.valueOf(basicoAdministrativo.calcular()));
            lblresultado.setVisible(true);
            lbltipoempleado.setText(basicoAdministrativo.realizarFuncion("Administrativas"));
            lbltipoempleado.setVisible(true);
            }else{
            basicoGerente.setHorasTrabajadas(Double.parseDouble(txthorasTrabajadas.getText()));
            basicoGerente.setValorHora(Double.parseDouble(txtvalorHora.getText()));
            lblresultado.setText(String.valueOf(basicoGerente.calcular()));
            lblresultado.setVisible(true);
            lbltipoempleado.setText(basicoGerente.realizarFuncion("Mandar"));
            lbltipoempleado.setVisible(true);
            
            }
        }
            }catch(NumberFormatException exception){
            JOptionPane.showMessageDialog(null, 
                    "No puedes dejar los campos vacíos o formato incorrecto (" + exception.getMessage()+")",
                    "Mensaje de información incompleta",
                    JOptionPane.ERROR_MESSAGE);
                    txthorasTrabajadas.requestFocus();
            }catch(Exception exception){
                JOptionPane.showMessageDialog(null,
                    "Información errónea (" + exception.getMessage()+")",
                    "Mensaje de información incompleta",
                    JOptionPane.ERROR_MESSAGE);
                    txthorasTrabajadas.setText("");
                    txtvalorHora.setText("");
            }
    }
        

    }//GEN-LAST:event_btncalcularActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

    private void rbempNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbempNormalActionPerformed
        rbempNormal.setSelected(true);
        rbempAdministrativo.setSelected(false);
        rbempGerente.setSelected(false);
    }//GEN-LAST:event_rbempNormalActionPerformed

    private void rbempAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbempAdministrativoActionPerformed
        rbempAdministrativo.setSelected(true);
        rbempNormal.setSelected(false);
        rbempGerente.setSelected(false);
    }//GEN-LAST:event_rbempAdministrativoActionPerformed

    private void rbempGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbempGerenteActionPerformed
        rbempAdministrativo.setSelected(false);
        rbempNormal.setSelected(false);
        rbempGerente.setSelected(true);
    }//GEN-LAST:event_rbempGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblresultado;
    private javax.swing.JLabel lblresultado1;
    private javax.swing.JLabel lbltipoempleado;
    private javax.swing.JRadioButton rbempAdministrativo;
    private javax.swing.JRadioButton rbempGerente;
    private javax.swing.JRadioButton rbempNormal;
    private javax.swing.JTextField txthorasTrabajadas;
    private javax.swing.JTextField txtvalorHora;
    // End of variables declaration//GEN-END:variables
}
